# Generated by Django 5.0.6 on 2024-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('aadhar', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('address', models.CharField(max_length=100)),
                ('parentname1', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('category', models.IntegerField(choices=[(1, 'General'), (2, 'OBC'), (3, 'SC'), (4, 'ST'), (5, 'PwD')])),
            ],
        ),
    ]
