# Generated by Django 5.0.6 on 2024-05-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='aadhar',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='parentname1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('total_12th', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField(blank=True, default=None, null=True)),
                ('cutoff', models.FloatField()),
                ('rank', models.IntegerField(blank=True, null=True, unique=True)),
                ('random_no', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.candidate')),
            ],
        ),
    ]
