# Generated by Django 5.0.6 on 2024-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_candidate_aadhar_alter_candidate_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='aadhar',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
