# Generated by Django 5.0.6 on 2024-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='aadhar',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
