# Generated by Django 5.0.6 on 2024-05-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_candidate_aadhar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
