# Generated by Django 5.0.6 on 2024-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('dob', models.DateField()),
                ('total_12th', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField(blank=True, default=None, null=True)),
                ('cutoff', models.FloatField()),
                ('rank', models.IntegerField(blank=True, null=True, unique=True)),
                ('random_no', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
        ),
    ]
