# Generated by Django 5.0.6 on 2024-05-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='rank',
            new_name='Rank',
        ),
    ]
