# Generated by Django 5.0.6 on 2024-05-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_rank_rank_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='Rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
